### PR TITLE
Add HorizontalChoice

### PR DESCRIPTION
**Pull request by matthijsgroen**
This implements #59 

To add this to the README, how should the PNG be generated? (any specs on sizes?)

### CODE REVIEW

**Comment by matthijsgroen** [comment]
Preview:
image

**Comment by matthijsgroen** [comment]
I now optimize the input and output track to take only the height into account for the items where the track has to go around:

image

**Comment by tabatkins** [comment]
Will review in a bit.

**Comment by matthijsgroen** [comment]
The effect is visible here: 

http://htmlpreview.github.io/?https://github.com/matthijsgroen/ebnf2railroad/blob/master/examples/ebnf.html

I'm using this library in a tool to create documentation based on ebnf: https://github.com/matthijsgroen/ebnf2railroad

**Comment by tabatkins** [comment]
Ah, very cool, I definitely see how this is useful!

However, the code needs some work; I know that it at minimum doesn't handle items with height well. (This isn't your fault; the code isn't well-documented in the first place.)  Here's an example:

```
Diagram(
  HorizontalChoice('a', Stack("1","2","3"), 'c'))
```

I'll play around with this and get it into a committable state. Thanks for the initial push!

**Comment by matthijsgroen** [comment]
Good catch! I will try to create a fix as well 😊

**Comment by matthijsgroen** [comment]
image

**Comment by matthijsgroen** [comment]
Only stacks as first and last element is still not correct

**Comment by matthijsgroen** [comment]
There is still one small "down" issue, will look at it later

**Comment by matthijsgroen** [comment]
@tabatkins I think all edge cases are covered now!

**Comment by tabatkins** [comment]
Phew, all right. While reviewing, I noticed the code still wasn't handling some corner cases correctly (handling all variations of large/small vertical separation and arc radius is tricky!), and generally was taking up more space than is necessary. In fixing these, I ended up rewriting it pretty much entirely. ^_^  But it's committed now and working beautifully, as far as I can tell.  I'll port it over to Python in a little bit.

Thanks so much for the idea and design!

(Also, btw, I also rewrote the entire thing as a JS module, using modern JS things like `class` and such. The older version still exists and the new HorizontalChoice exists in both versions. If you want something a little newer, feel free to just `import * as rr from "./railroad.js";` ^_^)

**Pull request closed without merging**
