### PR TITLE
Escape markdown text characters with HTML entities to prevent breaking when e...

### PR DESCRIPTION
**Pull request by jonathanKingston**
...mbedded in other formats #22

### CODE REVIEW

**Comment by tabatkins** [comment]
No, escaping all text characters is way too crazy.  I'm okay with escaping the chars that Markdown treats specially: ``*_`[]`` I guess?

**Comment by jonathanKingston** [comment]
@tabatkins updated, I'm glad you drew the line there. I wasn't sure where to cut the escaping so presumed escaping everything was the safest.

I added in `<` as before, do you want ampersand escaping just to be safe?

**Comment by tabatkins** [comment]
Yes, `<` and `&` have to be escaped for safe display in HTML.

**Comment by jonathanKingston** [comment]
@tabatkins ready for review again. Thanks.

**Comment by tabatkins** [comment]
All right, let's try this out.

**Pull request merged**
